### ISSUE TITLE
Including user data even if user deleting is missing 'moodle/backup:userinfo' capability

### ISSUE THREAD

**Issue by rlorenzo** [unikent/moodle-local_recyclebin#16]
On our system we do not allow instructors to backup user data by not allowing the 'moodle/backup:userinfo' capability for their role. We do this to protect user data.

However, a common use case that we want the recycle bin to solve is being able to restore a quiz or assignment that has student submissions if they are accidently deleted.

We cannot figure out a clean way to make this plugin include user data even if they normally cannot do it in the Moodle backup procedure. Got any ideas of how to accomplish that?

**Comment by sk-unikent** [comment]
It might make sense to set the current user to get_admin() when we backup and restore?
We want the plugin to backup/restore everything as it is regardless of the current user's capabilities.
