### ISSUE TITLE
Icons for Delete/Restore do not show up for base Moodle theme

### ISSUE THREAD

**Issue by rlorenzo** [unikent/moodle-local_recyclebin#19]
See attached image:

![screen shot 2015-08-12 at 5 16 15 pm](https://cloud.githubusercontent.com/assets/349765/9239957/ef81d35a-4115-11e5-9160-fd219c92f28d.png)

On a base version of Moodle with the core theme the icons are not showing up. That is because the icons depend on the theme having Font-Awesome icon set. Need a suitable workaround for the problem.

**Comment by ande7587** [comment]
Hello, I have a two additional issues to report about this plugin.

The first is that the recycle bin icon does not show up unless something is deleted, which means most people will never know it exists

The second issue is that when you click empty recycle bin, there is no confirmation explaining that this deletes everything permanently.

**Comment by rlorenzo** [comment]
I see you fixed this in https://github.com/unikent/moodle-local_recyclebin/commit/2b27a02a7d14ab29a0550d15c1fc9434cde25ccd
