### ISSUE TITLE
No confirmation for empty recycle bin

### ISSUE THREAD

**Issue by ande7587** [unikent/moodle-local_recyclebin#22]
This should ask the user if they are sure they want to delete all items forever, to be similar to other software that use a recycle bin feature

**Comment by rlorenzo** [comment]
We have a patch for this. @sk-unikent Once we get it ready I will make a pull request. This is a branch we are working on: https://github.com/ccle/moodle-local_recyclebin/commits/feature/CCLE-5298-recycle-bin-refinements

**Comment by rlorenzo** [comment]
This is fixed in https://github.com/unikent/moodle-local_recyclebin/pull/24
