### ISSUE TITLE
The front page course can have id <> 1

### ISSUE THREAD

**Issue by mudrd8mz** [unikent/moodle-local_recyclebin#30]
The code at https://github.com/unikent/moodle-local_recyclebin/blob/master/lib.php#L38 checks for

```
// Only add this settings item on non-site course pages.
if (!$PAGE->course or $PAGE->course->id == 1) {
```

Instead of hard-coded 1, the core constant `SITEID` should be used as there are valid cases where the site course has different id.

**Comment by sk-unikent** [comment]
Well spotted, thanks!
