### ISSUE TITLE
One hard-wired English language string in Recycle bin plugin

### ISSUE THREAD

**Issue by germanvaleroelizondo** [unikent/moodle-local_recyclebin#32]
Hi,

I like your recycle bin plugin for Moodle 2.9  a lot.

I translated the English language strings in AMOS (https://lang.moodle.org/) for the Mexican Spanish language pack and it works beautifully ...
... except that the name itself of the plugin appears in English inside the Administration block and in a few other places. Plese see the attached screen dump and notice correctly translated language strings inside most green rectangles and original hard-wired English text (Recycle bin)  inside the upmost rectangle.

I already purged the text language caches.

BTW; I hope you don't mind that I did a Moodle Docs page for this plugin at https://docs.moodle.org/all/es/local/Recycle_bin, so that the documentation for installing this plugin can be very easily translated into several languages (spanish language to be soon). 

![recycle bin is translated almost all of its strings](https://cloud.githubusercontent.com/assets/2671923/9472376/8a82b492-4b1a-11e5-9e1e-545aa4024b6c.png)

**Comment by sk-unikent** [comment]
Thanks for the translations! I have fixed this in the latest version (1.4).
I'll get to work on the documentation - I've been meaning to!
