### ISSUE TITLE
Try to get rid of the core hack

### ISSUE THREAD

**Issue by abias** [unikent/moodle-local_recyclebin#38]
Hi Skylar,

I already wrote this on https://moodle.org/plugins/view/local_recyclebin before I realized that you have a Github issue tracker for this plugin. Sorry for the double post.

I think you could improve the necessary core hack by a) throwing a general event in course_delete_module() and catching this event within your plugin instead of notifying your module directly b) creating an issue on tracker.moodle.org to include throwing this event into Moodle core.

How do you think about that?

Thanks,
Alex

**Comment by sk-unikent** [comment]
There has been a little discussion about that, David Mudrák commented:

> With regards to the hook, the thing is that there was no agreement achieved yet
> on how the hooks should be actually implemented. You may wish to check
> https://docs.moodle.org/dev/Hooks_spec for details. I do not personally think
> that event API would be appropriate solution for this case, even if Moodle has
> nothing better to offer :-/

I doubt a "pre-cm-deleted" event would gain much traction.

**Comment by abias** [comment]
Well, you're right. I missed that point in the discussion. 
But at the moment the discussion about the hooks spec seems not very active to me. On the other hand, the events system is there and could be (ab)used.

If you look at https://docs.moodle.org/dev/Event_2#Existing_events, there's already core\event\course_module_deleted and personally I don't know any good reason why there shouldn't be a core\event\course_module_pre_deleted.

Of course, if you just put a ticket in the tracker and wait for votes and a HQ developer to develop the feature, you probably will wait forever. But if you create a patch and submit it for integration in the tracker, a HQ developer will have to have a look at the patch and it might be integrated :)

Thanks,
Alex

**Comment by sk-unikent** [comment]
This plugin has been merged into Moodle 3.1
