### ISSUE TITLE
Recycle bin cleanup task is failing

### ISSUE THREAD

**Issue by rlorenzo** [unikent/moodle-local_recyclebin#40]
[vagrant@localhost moodle]$ php admin/tool/task/cli/schedule_task.php --execute=\local_recyclebin\task\clean_recyclebin
Scheduled task: Clean recycle bin
[RecycleBin] Deleting item 1...
Stacktrace:

```
Notice: Undefined property: stdClass::$course in /vagrant/moodle/local/recyclebin/classes/task/clean_recyclebin.php on line 58

Call Stack:
    0.0003     261592   1. {main}() /vagrant/moodle/admin/tool/task/cli/schedule_task.php:0
    0.5692   17385688   2. local_recyclebin\task\clean_recyclebin->execute() /vagrant/moodle/admin/tool/task/cli/schedule_task.php:131
```

The problem is that following query only returns ID:

$items = $DB->get_recordset_select('local_recyclebin', 'deleted < ?', array($deletefrom), '', 'id');

It should get the full record.

**Comment by rlorenzo** [comment]
We are working on a patch within the next week or so if you don't have time to patch it. We hope to also include a PHPunit test.

**Comment by sk-unikent** [comment]
Thanks for reporting this @rlorenzo - I've submitted a patch to master.
