### ISSUE TITLE
Old task not cleaned up

### ISSUE THREAD

**Issue by rlorenzo** [unikent/moodle-local_recyclebin#45]
I are running the latest master on our TEST server and updated our plugins. But when I viewed the scheduled tasks I see this error:

Failed to load task: \local_recyclebin\task\clean_recyclebin
line 255 of /lib/classes/task/manager.php: call to debugging()
line 377 of /lib/classes/task/manager.php: call to core\task\manager::scheduled_task_from_record()
line 121 of /admin/tool/task/scheduledtasks.php: call to core\task\manager::get_all_scheduled_tasks()

It seems that the splitting of the tasks (https://github.com/unikent/moodle-local_recyclebin/commit/deb545c812d3141260c2378607c7cc91428ddfac) didn't clean up the old task. Is that a core Moodle issue? I am running Moodle 2.7.10.

**Comment by sk-unikent** [comment]
Ah that used to be a core issue - I thought it got fixed in 2.7 but MDL-50532 seems to suggest not.
