### ISSUE TITLE
Separate category recycle bin out?

### ISSUE THREAD

**Issue by sk-unikent** [unikent/moodle-local_recyclebin#47]
Maybe we should move the category recycle bin out to another plugin to reduce the code complexity..

**Comment by rlorenzo** [comment]
Is this open to a vote? I say keep it in one. It is simpler for maintenance for us.

**Comment by sk-unikent** [comment]
This is more about MDL-48012 - I'm working on porting the activity side of this plugin over to core.
If that gets accepted etc it would _probably_ be worth picking out the category bit for MOODLE_31_STABLE and above. We hardly use the category recycle bin here though so I'm not sure it's worth us maintaining that..
