### ISSUE TITLE
Capability to empty recycle bins gone with latest version - reason?

### ISSUE THREAD

**Issue by Kathrin84** [unikent/moodle-local_recyclebin#49]
Hi, 

we're using your plugin and like it very much. Now that you've released a new version, I had a look at the changes and saw that there were some changes to the capabilities.
The capability to empty a recycle bin is gone and I'm wondering what the reasons were for you to changing this?

For my understanding, the possibility to be able to empty a recycle bin should not be withdrawn. So I just wanted to know what your reasons are.

Cheers,
Kathrin

**Comment by sk-unikent** [comment]
Hello!
There is still the capacity to empty the recycle bin it just requires the "delete" capability instead now.
If you can delete all the items, you can empty it, so from a user experience point of view it would be silly to allow a user to delete everything and yet not empty.

**Comment by Kathrin84** [comment]
Okay, now I see that the button to empty the recycle bin is there again. It was somehow gone in my system and so users with the capability to delete could only delete single items.
And I thought that it depends to this empty capability and didn't understand why it has been removed.
Sorry for the inconveniences!
