### ISSUE TITLE
Admin settings checkboxes to temporarily disable recycle bin not available

### ISSUE THREAD

**Issue by Kathrin84** [unikent/moodle-local_recyclebin#50]
Hi,

I've got a new issue. Directly when updating your plugin, we get those messages:
Warning: in_array() expects parameter 2 to be array, integer given in /var/www/html/moodle_dev/lib/adminlib.php on line 3192

Warning: in_array() expects parameter 2 to be array, integer given in /var/www/html/moodle_dev/lib/adminlib.php on line 3197

Furthermore, comparing your code to the gui, in the code are chechboxes impelemented (enablecourse and enablecategory) that are not displayed in our system (assuming due to this message):
![settings](https://cloud.githubusercontent.com/assets/4711883/11235880/923b9f34-8dd5-11e5-8d84-bcc9931d8eb7.png)

Cheers,
Kathrin

**Comment by sk-unikent** [comment]
I can't seem to replicate this! What version of Moodle are you running?

**Comment by Kathrin84** [comment]
Right now we're using Moodle 2.9.2+ (Build: 20151020).

**Comment by sk-unikent** [comment]
Could you update to the master branch and let me know if that fixes it?

**Comment by Kathrin84** [comment]
Great! Yes, it fixed this issue. Thanks! :)
