### ISSUE TITLE
Mdl 2.7, mdl 3.0 - Delete any single item in a recycling bin and the last item gets deleted instead

### ISSUE THREAD

**Issue by markchaneyuk** [unikent/moodle-local_recyclebin#62]
Regardless of which item you delete in the recycling bin the last item will always be deleted. E.g. if there are 5 items in the bin, and you delete the second item, the bottom gets deleted. 

After investigation I think that this is due to a javascript bug. We have found the error in version 1.4 of your plugin, but, as we are upgrading to Moodle 3, I have also downloaded your version 3 plugin and, after looking at the javascript, I can see that the bug hasn't been fixed. 

File: module.js
Lines 27 to 38. 

The intention is to present a confirmation button to the user and then, assuming a positive confirmation, redirect them back to the index page with the correct parameters for which item to delete in the ULR. 

I think the following is happening (I may be wrong??) Unfortunately the url that is being passed to window.location is a combination of ALL href's for all of the links that contain the class of recycle-bin-delete. var = urldelete = this.get('href'); will get all hrefs from this, where, in your code, 'this' is the whole Y space and not the actual link that was clicked. I think changing this.get('href'); to e.get('href') may fix it, but I personally would actually add an extra attribute to the link, e.g. called resourceid and get that from the clicked object rather than rely on the href attribute. 

If you add an alert(urldelete); after the variable is initialized then you will see that the variable contains all of the url's from all of the X links (those with the class recycle-bin-delete) concatenated together.  

Anyway, at present, the delete functionality of the plugin is unusable. 

Mark

**Comment by sk-unikent** [comment]
I've pushed a fix to master - thanks for reporting this!
